default: &default
  api_token: '98f7ca6cc1b969430492d0c8378fc4ce'
  account_id: '63c332e2-9a1b-44b3-8699-1bf2a6b96d43'

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
  api_token: <%= ENV['IUGU_API_TOKEN'] %>
  account_id: <%= ENV['IUGU_ACCOUNT_ID'] %>
